#!/bin/bash
to_decimal(){r=0 for((i=0 i<${#1} i++)) do d=${2%%${1:i:1}*} r=$((r*${#2}+${#d}));done echo $r } from_decimal(){n=$1;b=${#2} [[ $n -eq 0 ]]&&echo "${2:0:1}"&&return r= while((n)) do r=${2:n%b:1}$r n=$((n/b)) done echo $r}  from_decimal $(( $(to_decimal "$WATER" water) + $(to_decimal "$STIR" stir) )) bestchol
