#!/usr/bin/env bash
# Transfers a file to a remote ALX server using SCP with preconfigured key

if [ "$#" -lt 3 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME"
  exit 1
fi

FILE=$1
SERVER_IP=$2
USERNAME=$3

scp -o StrictHostKeyChecking=no "$FILE" "$USERNAME@$SERVER_IP:~/"
