#!/usr/bin/env bash
# Transfers a file to a remote server using SCP with key-based authentication

if [ "$#" -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

FILE=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=$4

scp -i "$ssh bff57259b463@bff57259b463.af077e84.alx-cod.online" -o StrictHostKeyChecking=no "$FILE" "$bff57259b463@$44.212.45.182:~/"
