#!/usr/bin/env bash
# Configures Nginx to add a custom HTTP header X-Served-By with the server's hostname

# Ignore SC2154 warning for hostname usage in shellcheck

# Update package lists
apt-get update -y

# Install nginx if not installed
if ! command -v nginx > /dev/null; then
    apt-get install -y nginx
fi

# Get hostname
server_hostname=$(hostname)

# Configure custom header by adding it inside /etc/nginx/conf.d/custom_header.conf
cat > /etc/nginx/conf.d/custom_header.conf <<EOF
add_header X-Served-By "$server_hostname";
EOF

# Test nginx config and reload if OK
nginx -t && service nginx reload
